# /Users/alex/WebDevelopment/gonetotheforest/netlify.toml
[build]
  command = "npm install && ./gf-convert_obsidian_links.sh && hugo --gc --minify --buildFuture && npx pagefind --site public"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.147.4"
